# =============================================================================
# Description: This file contains the test cases for Aromatics.
# =============================================================================
from .case import Case


aromatics_cases = [
    Case(
        "C1=CC2=CC=CC=CC2=C1",
        "smiles",
        "aromatics",
        unifac_result={"ACH": 8, "AC": 2},
        psrk_result={"ACH": 8, "AC": 2},
        joback_result={"ring=CH-": 8, "ring=C<": 2},
    ),
    Case(
        "C1=CC=CC=CC=CC=CC=CC=CC=CC=C1",
        "smiles",
        "aromatics",
        unifac_result={"ACH": 18},
        psrk_result={"ACH": 18},
        joback_result={"ring=CH-": 18},
    ),
    Case(
        "C1=CC=CC=CC=CC=CC=CC=C1",
        "smiles",
        "aromatics",
        unifac_result={"ACH": 14},
        psrk_result={"ACH": 14},
        joback_result={"ring=CH-": 14},
    ),
    Case(
        "C1=CC=C2C(=C1)C=CC3=CC=CC=C32",
        "smiles",
        "aromatics",
        commentary="phenanthrene",
        unifac_result={"ACH": 10, "AC": 4},
        psrk_result={"ACH": 10, "AC": 4},
        joback_result={"ring=CH-": 10, "ring=C<": 4},
    ),
    Case(
        "C1=CC=C2C=C3C=CC=CC3=CC2=C1",
        "smiles",
        "aromatics",
        commentary="anthracene",
        unifac_result={"ACH": 10, "AC": 4},
        psrk_result={"ACH": 10, "AC": 4},
        joback_result={"ring=CH-": 10, "ring=C<": 4},
    ),
    Case(
        "C=C(C1=CC=CC=C1)C2=CC=CC=C2",
        "smiles",
        "aromatics",
        commentary="1,1-Diphenylethylene",
        unifac_result={"ACH": 10, "AC": 2, "CH2=C": 1},
        psrk_result={"ACH": 10, "AC": 2, "CH2=C": 1},
        joback_result={"=CH2": 1, "=C<": 1, "ring=CH-": 10, "ring=C<": 2},
    ),
    Case(
        "C1=CC=C(C=C1)C2=CC=CC=C2",
        "smiles",
        "aromatics",
        commentary="biphenyl",
        unifac_result={"ACH": 10, "AC": 2},
        psrk_result={"ACH": 10, "AC": 2},
        joback_result={"ring=CH-": 10, "ring=C<": 2},
    ),
    Case(
        "C1=CC=CC=C1",
        "smiles",
        "aromatics",
        commentary="benzene",
        unifac_result={"ACH": 6},
        psrk_result={"ACH": 6},
        joback_result={"ring=CH-": 6},
    ),
    Case(
        "C=CC1=CC=CC=C1",
        "smiles",
        "aromatics",
        commentary="styrene",
        unifac_result={"AC": 1, "CH2=CH": 1, "ACH": 5},
        psrk_result={"AC": 1, "CH2=CH": 1, "ACH": 5},
        joback_result={"=CH2": 1, "=CH-": 1, "ring=CH-": 5, "ring=C<": 1},
    ),
    Case(
        "CC(C1=CC=CC=C1)(C(=O)O)O",
        "smiles",
        "aromatics",
        commentary="Atrolactic acid",
        unifac_result={
            "ACH": 5,
            "AC": 1,
            "OH": 1,
            "CH3": 1,
            "C": 1,
            "COOH": 1,
        },
        psrk_result={"ACH": 5, "AC": 1, "OH": 1, "CH3": 1, "C": 1, "COOH": 1},
        joback_result={
            "-CH3": 1,
            ">C<": 1,
            "ring=CH-": 5,
            "ring=C<": 1,
            "-OH (alcohol)": 1,
            "-COOH (acid)": 1,
        },
    ),
    Case(
        "CC(=CC1=CC=CC=C1)C=C",
        "smiles",
        "aromatics",
        commentary="1-Phenyl-2-methyl-1,3-butadiene",
        unifac_result={"ACH": 5, "AC": 1, "CH=C": 1, "CH2=CH": 1, "CH3": 1},
        psrk_result={"ACH": 5, "AC": 1, "CH=C": 1, "CH2=CH": 1, "CH3": 1},
        joback_result={
            "-CH3": 1,
            "=CH2": 1,
            "=CH-": 2,
            "=C<": 1,
            "ring=CH-": 5,
            "ring=C<": 1,
        },
    ),
    Case(
        "C=CCCC1=C2C=CC=CC2=CC3=CC=CC=C31",
        "smiles",
        "aromatics",
        commentary="9-(3-Butenyl)anthracene",
        unifac_result={"ACH": 9, "ACCH2": 1, "AC": 4, "CH2": 1, "CH2=CH": 1},
        psrk_result={"ACH": 9, "ACCH2": 1, "AC": 4, "CH2": 1, "CH2=CH": 1},
        joback_result={
            "-CH2-": 2,
            "=CH2": 1,
            "=CH-": 1,
            "ring=CH-": 9,
            "ring=C<": 5,
        },
    ),
    Case(
        "CC1=C2C=CC=CC2=CC3=CC=CC=C13",
        "smiles",
        "aromatics",
        commentary="9-Methylanthracene",
        unifac_result={"ACH": 9, "ACCH3": 1, "AC": 4},
        psrk_result={"ACH": 9, "ACCH3": 1, "AC": 4},
        joback_result={"-CH3": 1, "ring=CH-": 9, "ring=C<": 5},
    ),
    Case(
        "CC1=CC(=CC=C1)C2=CC=CC=C2",
        "smiles",
        "aromatics",
        commentary="3-Methylbiphenyl",
        unifac_result={"ACH": 9, "ACCH3": 1, "AC": 2},
        psrk_result={"ACH": 9, "ACCH3": 1, "AC": 2},
        joback_result={"-CH3": 1, "ring=CH-": 9, "ring=C<": 3},
    ),
    Case(
        "CCC1=C(C=CC(=C1C)C)C",
        "smiles",
        "aromatics",
        commentary="1,2,4-Trimethyl-3-Ethylbenzene",
        unifac_result={"ACH": 2, "ACCH3": 3, "ACCH2": 1, "CH3": 1},
        psrk_result={"ACH": 2, "ACCH3": 3, "ACCH2": 1, "CH3": 1},
        joback_result={"-CH3": 4, "-CH2-": 1, "ring=CH-": 2, "ring=C<": 4},
    ),
    Case(
        "CCC1=CC(=CC=C1)C(C)(C)C",
        "smiles",
        "aromatics",
        commentary="1-t-Butyl-3-ethylbenzene",
        unifac_result={"ACH": 4, "ACCH2": 1, "CH3": 4, "AC": 1, "C": 1},
        psrk_result={"ACH": 4, "ACCH2": 1, "CH3": 4, "AC": 1, "C": 1},
        joback_result={
            "-CH3": 4,
            "-CH2-": 1,
            ">C<": 1,
            "ring=CH-": 4,
            "ring=C<": 2,
        },
    ),
    Case(
        "CCC1=CC=CC(=C1C)C",
        "smiles",
        "aromatics",
        commentary="1-Ethyl-2,3-dimethylbenzene",
        unifac_result={"ACH": 3, "ACCH2": 1, "ACCH3": 2, "CH3": 1},
        psrk_result={"ACH": 3, "ACCH2": 1, "ACCH3": 2, "CH3": 1},
        joback_result={"-CH3": 3, "-CH2-": 1, "ring=CH-": 3, "ring=C<": 3},
    ),
    Case(
        "CCC1=CC=CC=C1C",
        "smiles",
        "aromatics",
        commentary="1-Ethyl-2-methylbenzene",
        unifac_result={"ACH": 4, "ACCH3": 1, "ACCH2": 1, "CH3": 1},
        psrk_result={"ACH": 4, "ACCH3": 1, "ACCH2": 1, "CH3": 1},
        joback_result={"-CH3": 2, "-CH2-": 1, "ring=CH-": 4, "ring=C<": 2},
    ),
    Case(
        "CCC1=CC=C(C=C1)C(C)C",
        "smiles",
        "aromatics",
        commentary="Benzene, 1-ethyl-4-(1-methylethyl)-",
        unifac_result={"ACH": 4, "ACCH": 1, "ACCH2": 1, "CH3": 3},
        psrk_result={"ACH": 4, "ACCH": 1, "ACCH2": 1, "CH3": 3},
        joback_result={
            "-CH3": 3,
            "-CH2-": 1,
            ">CH-": 1,
            "ring=CH-": 4,
            "ring=C<": 2,
        },
    ),
    Case(
        "C1=CC(=CC=C1CO)O",
        "smiles",
        "aromatics",
        commentary="Gastrodigenin",
        unifac_result={"ACH": 4, "ACOH": 1, "ACCH2": 1, "OH": 1},
        psrk_result={"ACH": 4, "ACOH": 1, "ACCH2": 1, "OH": 1},
        joback_result={
            "-CH2-": 1,
            "ring=CH-": 4,
            "ring=C<": 2,
            "-OH (alcohol)": 1,
            "-OH (phenol)": 1,
        },
    ),
    Case(
        "CC(C)C1=CC=CC=C1",
        "smiles",
        "aromatics",
        commentary="cumene",
        unifac_result={"CH3": 2, "ACH": 5, "ACCH": 1},
        psrk_result={"CH3": 2, "ACH": 5, "ACCH": 1},
        joback_result={"-CH3": 2, ">CH-": 1, "ring=CH-": 5, "ring=C<": 1},
    ),
    Case(
        "CCC1=CC=CC=C1",
        "smiles",
        "aromatics",
        commentary="ethylbenzene",
        unifac_result={"CH3": 1, "ACH": 5, "ACCH2": 1},
        psrk_result={"CH3": 1, "ACH": 5, "ACCH2": 1},
        joback_result={"-CH3": 1, "-CH2-": 1, "ring=CH-": 5, "ring=C<": 1},
    ),
    Case(
        "CC1=CC=CC=C1",
        "smiles",
        "aromatics",
        commentary="toluene",
        unifac_result={"ACH": 5, "ACCH3": 1},
        psrk_result={"ACH": 5, "ACCH3": 1},
        joback_result={"-CH3": 1, "ring=CH-": 5, "ring=C<": 1},
    ),
    Case(
        "C1=CC=C(C=C1)O",
        "smiles",
        "aromatics",
        commentary="phenol",
        unifac_result={"ACH": 5, "ACOH": 1},
        psrk_result={"ACH": 5, "ACOH": 1},
        joback_result={"ring=CH-": 5, "ring=C<": 1, "-OH (phenol)": 1},
    ),
]
