# =============================================================================
# Complex molecules (mix alot of groups) test cases
# =============================================================================
from .case import Case


complex_cases = [
    Case(
        identifier="CCCC1=C(COC(C)(C)COC(=O)OCC)C=C(CC2=CC=CC=C2)C=C1",
        identifier_type="smiles",
        cases_module="complex",
        unifac_result={
            "CH3": 4,
            "C": 1,
            "ACH": 8,
            "ACCH2": 2,
            "CH2O": 2,
            "COO": 1,
            "CH2": 2,
            "AC": 2,
        },
        psrk_result={
            "CH3": 4,
            "C": 1,
            "ACH": 8,
            "ACCH2": 2,
            "CH2O": 2,
            "COO": 1,
            "CH2": 2,
            "AC": 2,
        },
        joback_result={
            "-CH3": 4,
            "-CH2-": 6,
            ">C<": 1,
            "ring=CH-": 8,
            "ring=C<": 4,
            "-O- (non-ring)": 2,
            "-COO- (ester)": 1,
        },
    ),
    Case(
        identifier="CC(C)CC1=CC=C(C=C1)C(C)OC(C)(C)C",
        identifier_type="smiles",
        cases_module="complex",
        unifac_result={
            "CH3": 6,
            "C": 1,
            "ACH": 4,
            "ACCH2": 1,
            "CHO": 1,
            "CH": 1,
            "AC": 1,
        },
        psrk_result={
            "CH3": 6,
            "C": 1,
            "ACH": 4,
            "ACCH2": 1,
            "CHO": 1,
            "CH": 1,
            "AC": 1,
        },
        joback_result={
            "-CH3": 6,
            "-CH2-": 1,
            ">CH-": 2,
            ">C<": 1,
            "ring=CH-": 4,
            "ring=C<": 2,
            "-O- (non-ring)": 1,
        },
    ),
    Case(
        identifier="CCCC1=CC=C(CC(=O)OC)C=C1",
        identifier_type="smiles",
        cases_module="complex",
        unifac_result=[
            {"CH3": 2, "ACH": 4, "ACCH2": 1, "CH2COO": 1, "CH2": 1, "AC": 1},
            {"CH3": 2, "ACH": 4, "ACCH2": 2, "CH2": 1, "COO": 1},
        ],
        psrk_result=[
            {"CH3": 2, "ACH": 4, "ACCH2": 1, "CH2COO": 1, "CH2": 1, "AC": 1},
            {"CH3": 2, "ACH": 4, "ACCH2": 2, "CH2": 1, "COO": 1},
        ],
        joback_result={
            "-CH3": 2,
            "-CH2-": 3,
            "ring=CH-": 4,
            "ring=C<": 2,
            "-COO- (ester)": 1,
        },
    ),
    Case(
        identifier="C1=CC(=CC=C1COC(C)(C)C)CCC",
        identifier_type="smiles",
        cases_module="complex",
        unifac_result={
            "CH3": 4,
            "C": 1,
            "ACH": 4,
            "ACCH2": 1,
            "CH2O": 1,
            "CH2": 1,
            "AC": 1,
        },
        psrk_result={
            "CH3": 4,
            "C": 1,
            "ACH": 4,
            "ACCH2": 1,
            "CH2O": 1,
            "CH2": 1,
            "AC": 1,
        },
        joback_result={
            "-CH3": 4,
            "-CH2-": 3,
            ">C<": 1,
            "ring=CH-": 4,
            "ring=C<": 2,
            "-O- (non-ring)": 1,
        },
    ),
    Case(
        identifier="C13=C(C=C(C=C1)CC2=CC=CC(=C2)CC)CCCC3",
        identifier_type="smiles",
        cases_module="complex",
        unifac_result={"CH3": 1, "CH2": 2, "ACH": 7, "ACCH2": 4, "AC": 1},
        psrk_result={"CH3": 1, "CH2": 2, "ACH": 7, "ACCH2": 4, "AC": 1},
        joback_result={
            "-CH3": 1,
            "-CH2-": 2,
            "ring-CH2-": 4,
            "ring=CH-": 7,
            "ring=C<": 5,
        },
    ),
    Case(
        identifier="C13=C(C(=C(C(=C1C)C)CC2=C(C(=C(C(=C2C)CC)O[H])N([H])[H])C)C)CCCC3",  # noqa
        identifier_type="smiles",
        cases_module="complex",
        unifac_result={
            "CH3": 1,
            "CH2": 2,
            "ACCH3": 5,
            "ACCH2": 4,
            "ACOH": 1,
            "ACNH2": 1,
            "AC": 1,
        },
        psrk_result={
            "CH3": 1,
            "CH2": 2,
            "ACCH3": 5,
            "ACCH2": 4,
            "ACOH": 1,
            "ACNH2": 1,
            "AC": 1,
        },
        joback_result={
            "-CH3": 6,
            "-CH2-": 2,
            "ring-CH2-": 4,
            "ring=C<": 12,
            "-OH (phenol)": 1,
            "-NH2": 1,
        },
    ),
    Case(
        identifier="C1(=CC=CC=C1)COC(C)(C)C",
        identifier_type="smiles",
        cases_module="complex",
        unifac_result={"CH3": 3, "C": 1, "ACH": 5, "CH2O": 1, "AC": 1},
        psrk_result={"CH3": 3, "C": 1, "ACH": 5, "CH2O": 1, "AC": 1},
        joback_result={
            "-CH3": 3,
            "-CH2-": 1,
            ">C<": 1,
            "ring=CH-": 5,
            "ring=C<": 1,
            "-O- (non-ring)": 1,
        },
    ),
    Case(
        identifier="C1=CC=C(C=C1)CC2=CC=CC=C2",
        identifier_type="smiles",
        cases_module="complex",
        unifac_result={"ACH": 10, "ACCH2": 1, "AC": 1},
        psrk_result={"ACH": 10, "ACCH2": 1, "AC": 1},
        joback_result={"-CH2-": 1, "ring=CH-": 10, "ring=C<": 2},
    ),
    Case(
        identifier="C1(=CC=CC=C1)C(OC(C)(C)C)C",
        identifier_type="smiles",
        cases_module="complex",
        unifac_result={"CH3": 4, "C": 1, "ACH": 5, "CHO": 1, "AC": 1},
        psrk_result={"CH3": 4, "C": 1, "ACH": 5, "CHO": 1, "AC": 1},
        joback_result={
            "-CH3": 4,
            ">CH-": 1,
            ">C<": 1,
            "ring=CH-": 5,
            "ring=C<": 1,
            "-O- (non-ring)": 1,
        },
    ),
    Case(
        identifier="C12=CC=CC=C1COC2",
        identifier_type="smiles",
        cases_module="complex",
        unifac_result={"ACH": 4, "ACCH2": 1, "CH2O": 1, "AC": 1},
        psrk_result={"ACH": 4, "ACCH2": 1, "CH2O": 1, "AC": 1},
        joback_result={
            "ring-CH2-": 2,
            "ring=CH-": 4,
            "ring=C<": 2,
            "-O- (ring)": 1,
        },
    ),
]
