# =============================================================================
# Description: This file contains the test cases for the esters molecules.
# =============================================================================
from .case import Case


esters_cases = [
    Case(
        identifier="COC(=O)C=C",
        identifier_type="smiles",
        commentary="Methyl acrylate",
        cases_module="esters",
        unifac_result={"CH3": 1, "CH2=CH": 1, "COO": 1},
        psrk_result={"CH3": 1, "CH2=CH": 1, "COO": 1},
        joback_result={"-CH3": 1, "=CH2": 1, "=CH-": 1, "-COO- (ester)": 1},
    ),
    Case(
        identifier="COC(=O)C1C2CCC(CC1OC(=O)C1=CC=CC=C1)N2C",
        identifier_type="smiles",
        commentary="",
        cases_module="esters",
        unifac_result={
            "CH3": 1,
            "CH2": 3,
            "CH": 4,
            "CH3N": 1,
            "AC": 1,
            "ACH": 5,
            "COO": 2,
            "CH3N": 1,
        },
        psrk_result={
            "CH3": 1,
            "CH2": 3,
            "CH": 4,
            "CH3N": 1,
            "AC": 1,
            "ACH": 5,
            "COO": 2,
            "CH3N": 1,
        },
        joback_result={},
    ),
    Case(
        identifier="CCN(CC)CCOC(=O)C1=CC=C(N)C=C1",
        identifier_type="smiles",
        commentary="Procaine",
        cases_module="esters",
        unifac_result={
            "ACNH2": 1,
            "ACH": 4,
            "AC": 1,
            "COO": 1,
            "CH2": 3,
            "CH3": 2,
            "CH2N": 1,
        },
        psrk_result={
            "ACNH2": 1,
            "ACH": 4,
            "AC": 1,
            "COO": 1,
            "CH2": 3,
            "CH3": 2,
            "CH2N": 1,
        },
        joback_result={
            "-CH3": 2,
            "-CH2-": 4,
            "ring=CH-": 4,
            "ring=C<": 2,
            "-COO- (ester)": 1,
            "-NH2": 1,
            ">N- (non-ring)": 1,
        },
    ),
    Case(
        identifier="OCC(O)C1OC(=O)C(O)=C1O",
        identifier_type="smiles",
        commentary="Ascorbic acid",
        cases_module="esters",
        unifac_result={"COO": 1, "C=C": 1, "OH": 4, "CH": 2, "CH2": 1},
        psrk_result={"COO": 1, "C=C": 1, "OH": 4, "CH": 2, "CH2": 1},
        joback_result={
            "-CH2-": 1,
            ">CH-": 1,
            "ring>CH-": 1,
            "ring=C<": 2,
            "-OH (alcohol)": 4,
            "-COO- (ester)": 1,
        },
    ),
    Case(
        identifier="CCCCCCCCCCCC(=O)OCC(CO)OC(=O)CCCCCCCCCCC",
        identifier_type="smiles",
        commentary="Dilaurin",
        cases_module="esters",
        unifac_result={"CH3": 2, "CH2": 20, "CH2COO": 2, "OH": 1, "CH": 1},
        psrk_result={"CH3": 2, "CH2": 20, "CH2COO": 2, "OH": 1, "CH": 1},
        joback_result={
            "-CH3": 2,
            "-CH2-": 22,
            ">CH-": 1,
            "-OH (alcohol)": 1,
            "-COO- (ester)": 2,
        },
    ),
    Case(
        identifier="CC(=O)OC1=CC=CC=C1C(=O)O",
        identifier_type="smiles",
        commentary="Aspirin",
        cases_module="esters",
        unifac_result={"CH3COO": 1, "AC": 2, "ACH": 4, "COOH": 1},
        psrk_result={"CH3COO": 1, "AC": 2, "ACH": 4, "COOH": 1},
        joback_result={
            "-CH3": 1,
            "ring=CH-": 4,
            "ring=C<": 2,
            "-COOH (acid)": 1,
            "-COO- (ester)": 1,
        },
    ),
    Case(
        identifier="CC(=O)OC(C)(C)C",
        identifier_type="smiles",
        commentary="Tert-butyl acetate",
        cases_module="esters",
        unifac_result={"CH3COO": 1, "CH3": 3, "C": 1},
        psrk_result={"CH3COO": 1, "CH3": 3, "C": 1},
        joback_result={"-CH3": 4, ">C<": 1, "-COO- (ester)": 1},
    ),
    Case(
        identifier="CC(=O)OCC(COC(=O)C)OC(=O)C",
        identifier_type="smiles",
        commentary="Triacetin",
        cases_module="esters",
        unifac_result={"CH3COO": 3, "CH2": 2, "CH": 1},
        psrk_result={"CH3COO": 3, "CH2": 2, "CH": 1},
        joback_result={"-CH3": 3, "-CH2-": 2, ">CH-": 1, "-COO- (ester)": 3},
    ),
    Case(
        identifier="CCCCOC(=O)CC",
        identifier_type="smiles",
        commentary="butyl propanoate",
        cases_module="esters",
        unifac_result={"CH3": 2, "CH2": 3, "CH2COO": 1},
        psrk_result={"CH3": 2, "CH2": 3, "CH2COO": 1},
        joback_result={"-CH3": 2, "-CH2-": 4, "-COO- (ester)": 1},
    ),
    Case(
        identifier="CCCCOC(=O)C",
        identifier_type="smiles",
        commentary="butyl acetate",
        cases_module="esters",
        unifac_result={"CH3": 1, "CH2": 3, "CH3COO": 1},
        psrk_result={"CH3": 1, "CH2": 3, "CH3COO": 1},
        joback_result={"-CH3": 2, "-CH2-": 3, "-COO- (ester)": 1},
    ),
    Case(
        identifier="C1=CC=C(C=C1)OC=O",
        identifier_type="smiles",
        commentary="phenyl formate",
        cases_module="esters",
        unifac_result={"ACH": 5, "AC": 1, "HCOO": 1},
        psrk_result={"ACH": 5, "AC": 1, "HCOO": 1},
        joback_result={},
    ),
    Case(
        identifier="COC=O",
        identifier_type="smiles",
        commentary="methyl formate",
        cases_module="esters",
        unifac_result={"HCOO": 1, "CH3": 1},
        psrk_result={"HCOO": 1, "CH3": 1},
        joback_result={},
    ),
    Case(
        identifier="CCOC=O",
        identifier_type="smiles",
        commentary="ethyl formate",
        cases_module="esters",
        unifac_result={"HCOO": 1, "CH2": 1, "CH3": 1},
        psrk_result={"HCOO": 1, "CH2": 1, "CH3": 1},
        joback_result={},
    ),
]
