# =============================================================================
# Description: This file contains the test cases for the esthers molecules.
# =============================================================================
from .case import Case


esthers_cases = [
    Case(
        identifier="CCCCCCCCCCCC(=O)OCC(CO)OC(=O)CCCCCCCCCCC",
        identifier_type="smiles",
        cases_module="Dilaurin",
        commentary="esthers",
        r=None,
        q=None,
        unifac_result={"CH3": 2, "CH2": 20, "CH2COO": 2, "OH": 1, "CH": 1},
        psrk_result={"CH3": 2, "CH2": 20, "CH2COO": 2, "OH": 1, "CH": 1},
        joback_result={'-CH3': 2, '-CH2-': 22, '>CH-': 1, '-OH (alcohol)': 1, '-COO- (ester)': 2},
    ),
    Case(
        identifier="CC(=O)OC1=CC=CC=C1C(=O)O",
        identifier_type="smiles",
        cases_module="Aspirin",
        commentary="esthers",
        r=None,
        q=None,
        unifac_result={"CH3COO": 1, "AC": 2, "ACH": 4, "COOH": 1},
        psrk_result={"CH3COO": 1, "AC": 2, "ACH": 4, "COOH": 1},
        joback_result={'-CH3': 1, 'ring=CH-': 4, 'ring=C<': 2, '-COOH (acid)': 1, '-COO- (ester)': 1},
    ),
    Case(
        identifier="CC(=O)OC(C)(C)C",
        identifier_type="smiles",
        cases_module="Tert-butyl acetate",
        commentary="esthers",
        r=None,
        q=None,
        unifac_result={"CH3COO": 1, "CH3": 3, "C": 1},
        psrk_result={"CH3COO": 1, "CH3": 3, "C": 1},
        joback_result={'-CH3': 4, '>C<': 1, '-COO- (ester)': 1},
    ),
    Case(
        identifier="CC(=O)OCC(COC(=O)C)OC(=O)C",
        identifier_type="smiles",
        cases_module="Triacetin",
        commentary="esthers",
        r=None,
        q=None,
        unifac_result={"CH3COO": 3, "CH2": 2, "CH": 1},
        psrk_result={"CH3COO": 3, "CH2": 2, "CH": 1},
        joback_result={'-CH3': 3, '-CH2-': 2, '>CH-': 1, '-COO- (ester)': 3},
    ),
    Case(
        identifier="CCCCOC(=O)CC",
        identifier_type="smiles",
        cases_module="butyl propanoate",
        commentary="esthers",
        r=None,
        q=None,
        unifac_result={"CH3": 2, "CH2": 3, "CH2COO": 1},
        psrk_result={"CH3": 2, "CH2": 3, "CH2COO": 1},
        joback_result={'-CH3': 2, '-CH2-': 4, '-COO- (ester)': 1},
    ),
    Case(
        identifier="CCCCOC(=O)C",
        identifier_type="smiles",
        cases_module="butyl acetate",
        commentary="esthers",
        r=None,
        q=None,
        unifac_result={"CH3": 1, "CH2": 3, "CH3COO": 1},
        psrk_result={"CH3": 1, "CH2": 3, "CH3COO": 1},
        joback_result={'-CH3': 2, '-CH2-': 3, '-COO- (ester)': 1},
    ),
    Case(
        identifier="C1=CC=C(C=C1)OC=O",
        identifier_type="smiles",
        cases_module="phenyl formate",
        commentary="esthers",
        r=None,
        q=None,
        unifac_result={"ACH": 5, "AC": 1, "HCOO": 1},
        psrk_result={"ACH": 5, "AC": 1, "HCOO": 1},
        joback_result={},
    ),
    Case(
        identifier="COC=O",
        identifier_type="smiles",
        cases_module="methyl formate",
        commentary="esthers",
        r=None,
        q=None,
        unifac_result={"HCOO": 1, "CH3": 1},
        psrk_result={"HCOO": 1, "CH3": 1},
        joback_result={},
    ),
    Case(
        identifier="CCOC=O",
        identifier_type="smiles",
        cases_module="ethyl formate",
        commentary="esthers",
        r=None,
        q=None,
        unifac_result={"HCOO": 1, "CH2": 1, "CH3": 1},
        psrk_result={"HCOO": 1, "CH2": 1, "CH3": 1},
        joback_result={},
    )
]