# =============================================================================
# Description: This file contains the test cases for the particulars molecules
#
# Example, water, pyridine, etc. All the thing that are simple and basic but
# you cannot put anywhere else.
# =============================================================================
from .case import Case


particulars_cases = [
    Case(
        "O",
        "smiles",
        "particulars",
        "Water",
        unifac_result={"H2O": 1},
        psrk_result={"H2O": 1},
        joback_result={},
    ),
    Case(
        identifier="C1=COC(=C1)C=O",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={"FURFURAL": 1},
        psrk_result={"FURFURAL": 1},
        joback_result={
            "ring=CH-": 3,
            "ring=C<": 1,
            "-O- (ring)": 1,
            "O=CH- (aldehyde)": 1,
        },
    ),
    Case(
        identifier="CS(=O)C",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={"DMSO": 1},
        psrk_result={"DMSO": 1},
        joback_result={},
    ),
    Case(
        identifier="C=CC#N",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={"ACRY": 1},
        psrk_result={"ACRY": 1},
        joback_result={"=CH2": 1, "=CH-": 1, "-CN": 1},
    ),
    Case(
        identifier="BrCN(CC1=CC=NC=C1)C=O",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={"C5H4N": 1, "BR": 1, "HCON(CH2)2": 1},
        psrk_result={"C5H4N": 1, "BR": 1, "HCON(CH2)2": 1},
        joback_result={
            "-CH2-": 2,
            "ring=CH-": 4,
            "ring=C<": 1,
            "-Br": 1,
            "O=CH- (aldehyde)": 1,
            ">N- (non-ring)": 1,
            "-N= (ring)": 1,
        },
    ),
    Case(
        identifier="BrCN(CC1=CC=CC=C1)C=O",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={"ACH": 5, "BR": 1, "HCON(CH2)2": 1, "AC": 1},
        psrk_result={"ACH": 5, "BR": 1, "HCON(CH2)2": 1, "AC": 1},
        joback_result={
            "-CH2-": 2,
            "ring=CH-": 5,
            "ring=C<": 1,
            "-Br": 1,
            "O=CH- (aldehyde)": 1,
            ">N- (non-ring)": 1,
        },
    ),
    Case(
        identifier="CN(C)C=O",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={"DMF": 1},
        psrk_result={"DMF": 1},
        joback_result={"-CH3": 2, "O=CH- (aldehyde)": 1, ">N- (non-ring)": 1},
    ),
    Case(
        identifier="CCN(CC)C=O",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={"CH3": 2, "HCON(CH2)2": 1},
        psrk_result={"CH3": 2, "HCON(CH2)2": 1},
        joback_result={
            "-CH3": 2,
            "-CH2-": 2,
            "O=CH- (aldehyde)": 1,
            ">N- (non-ring)": 1,
        },
    ),
    Case(
        identifier="CN1CCCC1=O",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={"NMP": 1},
        psrk_result={"NMP": 1},
        joback_result={},
    ),
    Case(
        identifier="C1COCCN1",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={"MORPH": 1},
        psrk_result={"MORPH": 1},
        joback_result={"ring-CH2-": 4, "-O- (ring)": 1, ">NH (ring)": 1},
    ),
    Case(
        identifier="OC1=CSC=C1",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={"C4H3S": 1, "OH": 1},
        psrk_result={"C4H3S": 1, "OH": 1},
        joback_result={
            "ring=CH-": 3,
            "ring=C<": 1,
            "-OH (phenol)": 1,
            "-S- (ring)": 1,
        },
    ),
    Case(
        identifier="CC1=C(SC=C1)C",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={"C4H2S": 1, "CH3": 2},
        psrk_result={"C4H2S": 1, "CH3": 2},
        joback_result={
            "-CH3": 2,
            "ring=CH-": 2,
            "ring=C<": 2,
            "-S- (ring)": 1,
        },
    ),
    Case(
        identifier="C1=CSC=C1",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={"C4H4S": 1},
        psrk_result={"C4H4S": 1},
        joback_result={"ring=CH-": 4, "-S- (ring)": 1},
    ),
    Case(
        identifier="CC1=CC=CS1",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={"C4H3S": 1, "CH3": 1},
        psrk_result={"C4H3S": 1, "CH3": 1},
        joback_result={
            "-CH3": 1,
            "ring=CH-": 3,
            "ring=C<": 1,
            "-S- (ring)": 1,
        },
    ),
    Case(
        identifier="OC1=CC=CS1",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={"C4H3S": 1, "OH": 1},
        psrk_result={"C4H3S": 1, "OH": 1},
        joback_result={
            "ring=CH-": 3,
            "ring=C<": 1,
            "-OH (phenol)": 1,
            "-S- (ring)": 1,
        },
    ),
    Case(
        identifier="OC1=CSC=C1O",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={"C4H2S": 1, "OH": 2},
        psrk_result={"C4H2S": 1, "OH": 2},
        joback_result={
            "ring=CH-": 2,
            "ring=C<": 2,
            "-OH (phenol)": 2,
            "-S- (ring)": 1,
        },
    ),
    Case(
        identifier="OC1=CC(O)=CS1",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={"C4H2S": 1, "OH": 2},
        psrk_result={"C4H2S": 1, "OH": 2},
        joback_result={
            "ring=CH-": 2,
            "ring=C<": 2,
            "-OH (phenol)": 2,
            "-S- (ring)": 1,
        },
    ),
    Case(
        identifier="OC1=CC=C(O)S1",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={"C4H2S": 1, "OH": 2},
        psrk_result={"C4H2S": 1, "OH": 2},
        joback_result={
            "ring=CH-": 2,
            "ring=C<": 2,
            "-OH (phenol)": 2,
            "-S- (ring)": 1,
        },
    ),
    Case(
        identifier="N1C=CN=C1",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={"IMIDAZOL": 1},
        psrk_result={},
        joback_result={"ring=CH-": 3, ">NH (ring)": 1, "-N= (ring)": 1},
    ),
    Case(
        identifier="FC(F)(F)S(=O)(=O)[N-]S(=O)(=O)C(F)(F)F",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={"BTI": 1},
        psrk_result={},
        joback_result={},
    ),
    Case(
        identifier="hydrogen peroxide",
        identifier_type="name",
        cases_module="particulars",
        unifac_result={},
        psrk_result={},
        joback_result={},
    ),
    Case(
        identifier="methane",
        identifier_type="name",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"CH4": 1},
        joback_result={},
    ),
    Case(
        identifier="C1(=CC=CC=C1)OC(C)(C)C",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={},
        joback_result={
            "-CH3": 3,
            ">C<": 1,
            "ring=CH-": 5,
            "ring=C<": 1,
            "-O- (non-ring)": 1,
        },
    ),
    Case(
        identifier="[O-][O+]=O",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"O3": 1},
        joback_result={"-O- (non-ring)": 1, "=O (other than above)": 2},
    ),
    Case(
        identifier="C=C",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"H2C=CH2": 1},
        joback_result={"=CH2": 2},
    ),
    Case(
        identifier="C#C",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"CH=-CH": 1},
        joback_result={"CH": 2},
    ),
    Case(
        identifier="N",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"NH3": 1},
        joback_result={},
    ),
    Case(
        identifier="[C-]#[O+]",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"CO": 1},
        joback_result={},
    ),
    Case(
        identifier="S",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"H2S": 1},
        joback_result={},
    ),
    Case(
        identifier="N#N",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"N2": 1},
        joback_result={},
    ),
    Case(
        identifier="[Ar]",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"AR": 1},
        joback_result={},
    ),
    Case(
        identifier="C(=O)=O",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"CO2": 1},
        joback_result={"=C=": 1, "=O (other than above)": 2},
    ),
    Case(
        identifier="C",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"CH4": 1},
        joback_result={},
    ),
    Case(
        identifier="O=O",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"O2": 1},
        joback_result={"=O (other than above)": 2},
    ),
    Case(
        identifier="O=S=O",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"SO2": 1},
        joback_result={"=O (other than above)": 2, "-S- (non-ring)": 1},
    ),
    Case(
        identifier="[N]=O",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"NO": 1},
        joback_result={},
    ),
    Case(
        identifier="[N-]=[N+]=O",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"N2O": 1},
        joback_result={},
    ),
    Case(
        identifier="FS(F)(F)(F)(F)F",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"SF6": 1},
        joback_result={},
    ),
    Case(
        identifier="[He]",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"HE": 1},
        joback_result={},
    ),
    Case(
        identifier="[Ne]",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"NE": 1},
        joback_result={},
    ),
    Case(
        identifier="[Kr]",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"KR": 1},
        joback_result={},
    ),
    Case(
        identifier="[Xe]",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"XE": 1},
        joback_result={},
    ),
    Case(
        identifier="F",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"HF": 1},
        joback_result={},
    ),
    Case(
        identifier="Cl",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"HCL": 1},
        joback_result={},
    ),
    Case(
        identifier="Br",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"HBR": 1},
        joback_result={},
    ),
    Case(
        identifier="I",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"HI": 1},
        joback_result={},
    ),
    Case(
        identifier="C(=O)=S",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"COS": 1},
        joback_result={},
    ),
    Case(
        identifier="C1CO1",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={"CH2": 1, "CH2O": 1},
        psrk_result={"H2COCH2": 1},
        joback_result={"ring-CH2-": 2, "-O- (ring)": 1},
    ),
    Case(
        identifier="FF",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"F2": 1},
        joback_result={"-F": 2},
    ),
    Case(
        identifier="ClCl",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"CL2": 1},
        joback_result={"-Cl": 2},
    ),
    Case(
        identifier="BrBr",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"BR2": 1},
        joback_result={"-Br": 2},
    ),
    Case(
        identifier="C#N",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"HCN": 1},
        joback_result={},
    ),
    Case(
        identifier="N(=O)[O]",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"NO2": 1},
        joback_result={"=O (other than above)": 2, "-N= (non-ring)": 1},
    ),
    Case(
        identifier="C(F)(F)(F)F",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"CF4": 1},
        joback_result={">C<": 1, "-F": 4},
    ),
    Case(
        identifier="N(=O)Cl",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"CLNO": 1},
        joback_result={
            "-Cl": 1,
            "=O (other than above)": 1,
            "-N= (non-ring)": 1,
        },
    ),
    Case(
        identifier="CC(C)(C)N",
        identifier_type="smiles",
        cases_module="particulars",
        unifac_result={},
        psrk_result={"CH3": 3, "CNH2": 1},
        joback_result={"-CH3": 3, ">C<": 1, "-NH2": 1},
    ),
    Case(
        identifier="hydrogen",
        identifier_type="name",
        cases_module="particulars",
        unifac_result={},
        psrk_result={},
        joback_result={},
    ),
    # Case( TODO
    #     identifier="deuterium",
    #     identifier_type="name",
    #     cases_module="particulars",
    #     r=None,
    #     q=None,
    #     unifac_result={},
    #     psrk_result={},
    #     joback_result={},
    # ),
]
