# =============================================================================
# Description: Test cases for the insaturated hydrocarbons module.
#
# This module contains the test cases for insaturated hydrocarbons
# cyclics or aliphatic (not aromatic).
# =============================================================================
from .case import Case


unsaturated_hydrocarbons_cases = [
    Case(
        "CC=C(C)C1=C(C=CC=C1C=C)C(C)=C(C)C",
        "smiles",
        "insaturated hydrocarbons",
        unifac_result={
            "CH3": 5,
            "CH2=CH": 1,
            "CH=C": 1,
            "C=C": 1,
            "ACH": 3,
            "AC": 3,
        },
        psrk_result={
            "CH3": 5,
            "CH2=CH": 1,
            "CH=C": 1,
            "C=C": 1,
            "ACH": 3,
            "AC": 3,
        },
        joback_result={
            "-CH3": 5,
            "=CH2": 1,
            "=CH-": 2,
            "=C<": 3,
            "ring=CH-": 3,
            "ring=C<": 3,
        },
    ),
    Case(
        "CC=CC(C)=C(C)C=C",
        "smiles",
        "insaturated hydrocarbons",
        unifac_result={"CH2=CH": 1, "CH=CH": 1, "C=C": 1, "CH3": 3},
        psrk_result={"CH2=CH": 1, "CH=CH": 1, "C=C": 1, "CH3": 3},
        joback_result={"-CH3": 3, "=CH2": 1, "=CH-": 3, "=C<": 2},
    ),
    Case(
        "CC1=CCC2CC1C2(C)C",
        "smiles",
        "insaturated hydrocarbons",
        commentary="alpha-pinene",
        unifac_result={"CH3": 3, "CH2": 2, "CH": 2, "C": 1, "CH=C": 1},
        psrk_result={"CH3": 3, "CH2": 2, "CH": 2, "C": 1, "CH=C": 1},
        joback_result={
            "-CH3": 3,
            "ring-CH2-": 2,
            "ring>CH-": 2,
            "ring>C<": 1,
            "ring=CH-": 1,
            "ring=C<": 1,
        },
    ),
    Case(
        "CC1=CCC(CC1)C(=C)C",
        "smiles",
        "insaturated hydrocarbons",
        commentary="d-limonene",
        unifac_result={"CH3": 2, "CH2": 3, "CH": 1, "CH2=C": 1, "CH=C": 1},
        psrk_result={"CH3": 2, "CH2": 3, "CH": 1, "CH2=C": 1, "CH=C": 1},
        joback_result={
            "-CH3": 2,
            "=CH2": 1,
            "=C<": 1,
            "ring-CH2-": 3,
            "ring>CH-": 1,
            "ring=CH-": 1,
            "ring=C<": 1,
        },
    ),
    Case(
        "CC1=CCCC=C1C",
        "smiles",
        "insaturated hydrocarbons",
        commentary="2,3-Dimethyl-1,3-cyclohexadiene",
        unifac_result={"CH2": 2, "CH=C": 2, "CH3": 2},
        psrk_result={"CH2": 2, "CH=C": 2, "CH3": 2},
        joback_result={"-CH3": 2, "ring-CH2-": 2, "ring=CH-": 2, "ring=C<": 2},
    ),
    Case(
        "CCC(CCC1CCCC=C1)C2CCCC=C2",
        "smiles",
        "insaturated hydrocarbons",
        commentary="3,3'-(Pentane-1,3-diyl)dicyclohexene",
        unifac_result={"CH3": 1, "CH2": 9, "CH": 3, "CH=CH": 2},
        psrk_result={"CH3": 1, "CH2": 9, "CH": 3, "CH=CH": 2},
        joback_result={
            "-CH3": 1,
            "-CH2-": 3,
            ">CH-": 1,
            "ring-CH2-": 6,
            "ring>CH-": 2,
            "ring=CH-": 4,
        },
    ),
    Case(
        "C1CCC=CC1",
        "smiles",
        "insaturated hydrocarbons",
        commentary="cyclohexene",
        unifac_result={"CH2": 4, "CH=CH": 1},
        psrk_result={"CH2": 4, "CH=CH": 1},
        joback_result={"ring-CH2-": 4, "ring=CH-": 2},
    ),
    Case(
        "CC(=C(C)C)C",
        "smiles",
        "insaturated hydrocarbons",
        commentary="2,3-dimethylbutene-2",
        unifac_result={"C=C": 1, "CH3": 4},
        psrk_result={"C=C": 1, "CH3": 4},
        joback_result={"-CH3": 4, "=C<": 2},
    ),
    Case(
        "CC=C(C)C",
        "smiles",
        "insaturated hydrocarbons",
        commentary="2-methyl-2-butene",
        unifac_result={"CH=C": 1, "CH3": 3},
        psrk_result={"CH=C": 1, "CH3": 3},
        joback_result={"-CH3": 3, "=CH-": 1, "=C<": 1},
    ),
    Case(
        "CCC(=C)C",
        "smiles",
        "insaturated hydrocarbons",
        commentary="2-methyl-1-butene",
        unifac_result={"CH2": 1, "CH2=C": 1, "CH3": 2},
        psrk_result={"CH2": 1, "CH2=C": 1, "CH3": 2},
        joback_result={"-CH3": 2, "-CH2-": 1, "=CH2": 1, "=C<": 1},
    ),
    Case(
        "CCCC=CC",
        "smiles",
        "insaturated hydrocarbons",
        commentary="2-hexene",
        unifac_result={"CH2": 2, "CH=CH": 1, "CH3": 2},
        psrk_result={"CH2": 2, "CH=CH": 1, "CH3": 2},
        joback_result={"-CH3": 2, "-CH2-": 2, "=CH-": 2},
    ),
    Case(
        "CCCCC=C",
        "smiles",
        "insaturated hydrocarbons",
        commentary="1-hexene",
        unifac_result={"CH2": 3, "CH2=CH": 1, "CH3": 1},
        psrk_result={"CH2": 3, "CH2=CH": 1, "CH3": 1},
        joback_result={"-CH3": 1, "-CH2-": 3, "=CH2": 1, "=CH-": 1},
    ),
    Case(
        "C=C=C",
        "smiles",
        "insaturated hydrocarbons",
        unifac_result={},
        psrk_result={},
        joback_result={"=CH2": 2, "=C=": 1},
    ),
    Case(
        "CC=CC(C)C(C)=C=C",
        "smiles",
        "insaturated hydrocarbons",
        unifac_result={},
        psrk_result={},
        joback_result={
            "-CH3": 3,
            ">CH-": 1,
            "=CH2": 1,
            "=CH-": 2,
            "=C<": 1,
            "=C=": 1,
        },
    ),
    Case(
        identifier="CC#CC1=CC=CC=C1",
        identifier_type="smiles",
        cases_module="insaturated hydrocarbons",
        unifac_result={"CH3": 1, "ACH": 5, "AC": 1, "C=-C": 1},
        psrk_result={"CH3": 1, "ACH": 5, "AC": 1, "C=-C": 1},
        joback_result={"-CH3": 1, "C": 2, "ring=CH-": 5, "ring=C<": 1},
    ),
    Case(
        identifier="CCCCC#C",
        identifier_type="smiles",
        cases_module="insaturated hydrocarbons",
        unifac_result={"CH3": 1, "CH2": 3, "CH=-C": 1},
        psrk_result={"CH3": 1, "CH2": 3, "CH=-C": 1},
        joback_result={"-CH3": 1, "-CH2-": 3, "CH": 1, "C": 1},
    ),
    Case(
        identifier="CCCC#CC",
        identifier_type="smiles",
        cases_module="insaturated hydrocarbons",
        unifac_result={"CH3": 2, "CH2": 2, "C=-C": 1},
        psrk_result={"CH3": 2, "CH2": 2, "C=-C": 1},
        joback_result={"-CH3": 2, "-CH2-": 2, "C": 2},
    ),
]
