name: Publish to PyPI
on:
  release:
    types: [created]
  pull_request:

jobs:
  testing:
    uses: ipqa-research/ugropy/.github/workflows/ci.yml@main
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    needs: testing
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: do stuff
        run: echo "Publishing package..."
    